es6 field faculty: add marker value for missing value
ugent-library/biblio-backoffice pull request #1078
Opened 2023-04-26 09:47 UTC by nicolasfranck

Fixes #1075 

What it does: adds marker value `n/a` ("not assigned") to the list of values in the elasticsearch field `faculty`.

TODO: reindex publications and datasets in backoffice; frontend not needed.

Remarks:
* there was also a possibility to search for empty values (a sort of "must not exists" query), but the way that was done added too much complexity (e.g. now we filter out facet filters if there the filter has the same name of the facet, and it is a term filter). Anyway, in the url we still had to come up with a special value to query on.

2023-06-06 06:48 UTC, nicolasfranck commented
@nics @mietcls  will add support for missing year too? See #916

2023-08-29 13:36 UTC, nicolasfranck commented
to delete or split up? @netsensei @nics

2023-09-05 12:23 UTC, netsensei commented
@mietcls  I understand the question regarding missing field marker for faculties; but the other fields aren't mentioned in the issue #1075? It's unclear: is this PR finished, or do more fields need a "missing" option? Could you re-write / expand #1075 with the fields that need such a "missing" marker?

2023-09-06 07:21 UTC, mietcls commented
@netsensei this issue is referenced as well, @nicolasfranck closed it as a double, but this asks for the other ones as well: https://github.com/ugent-library/biblio-backoffice/issues/915

2023-09-08 10:06 UTC, nics requested changes

2023-09-08 11:13 UTC, nicolasfranck commented on internal/translations/translations.go
> +	message.SetString(language.English, "organization.n/a", "[missing]")
@nics the title of the facet is "Faculty". A bit strange to put "no affiliation" below that, not?

2023-09-08 11:55 UTC, nics commented on internal/translations/translations.go
> +	message.SetString(language.English, "organization.n/a", "[missing]")
yes but some organization.n/a could also be used for department, research group, ...

2023-09-19 12:28 UTC, nics approved these changes

2023-09-19 12:28 UTC, merged