Feature/screen estate: fix overflowing and misaligned fields + avoid mis-clicking
ugent-library/biblio-backoffice pull request #1200
Opened 2023-08-29 15:11 UTC by mietcls

Fixes https://github.com/ugent-library/biblio-backoffice/issues/744

2023-08-29 15:24 UTC, nics commented
hi @mietcls this can't be right: `This branch is [2 commits ahead](https://github.com/ugent-library/biblio-backoffice/compare/dev...feature/screen-estate), [205 commits behind](https://github.com/ugent-library/biblio-backoffice/compare/feature/screen-estate...dev) dev.`
trying to merge a branch from main into dev?

2023-08-30 07:20 UTC, mietcls commented
I think there's confusion about the flow we have. Can we clear this out? There are multiple visions on the branching and merging flow (e.g. main-branch-dev-main VS dev-branch-dev-main flow) and I thought I was adhering to the style proposed :-)

2023-08-31 15:02 UTC, mietcls commented
@nics Fixed it by merging dev into this branch, is this okay?
I will revert to this flow until new consensus arrives:
- main-branch-main for hotfixes
- dev-branch-dev for features

2023-09-08 09:41 UTC, nics requested changes

2023-09-08 09:41 UTC, nics commented on views/dataset/confirm_republish.gohtml
> +                <div class="bc-toolbar-left">
Tag isn't closed I think

2023-09-08 09:41 UTC, nics commented on views/dataset/confirm_delete_abstract.gohtml
> +                <div class="bc-toolbar-left">
Tag isn't closed

2023-09-08 09:41 UTC, nics commented on views/dataset/confirm_withdraw.gohtml
> +                <div class="bc-toolbar-left">
Tag isn't closed

2023-09-08 09:41 UTC, nics commented on views/dataset/edit_abstract.gohtml
> +                <div class="bc-toolbar-left">
Tag isn't closed

2023-09-08 09:41 UTC, nics commented on views/shared/_contributor_summary.gohtml
> +        <span class="mr-3">{{.Contributor.Name}}</span>
Should be
```
<span class="mr-3">{{.Contributor.Person.FullName}}</span>
```

2023-09-08 13:27 UTC, nics approved these changes

2023-09-08 13:28 UTC, merged