Enhancement/plato enhancements
ugent-library/biblio-backoffice pull request #1681
Opened 2024-07-30 15:50 UTC by mietcls

Incorporated some feedback gotten after the first Plato release

- Filters were not responsive enough for split screen
- Linking datasets to publications and vice versa looked different from projects, now aligned
- Added a dot to "last edit by"
- Improved copy and button positioning for the next Plato suggestions release
- Add suggested departments in overview

These tasks are part of #1623

2024-08-06 13:49 UTC, verheyenkoen requested changes
Some tests are broken because of these changes. Should be easy to fix.

2024-08-06 13:49 UTC, verheyenkoen commented on views/dataset/add_publication_dialog.templ
> +					Select one or more publications as already registered in Biblio. <a href="https://onderzoektips.ugent.be/en/tips/00002061/" target="_blank">View documentation <i class="if if--small if-external-
Is the word "as" intended here?

2024-08-06 13:49 UTC, verheyenkoen commented on views/publication/add_dataset.templ
> +					Select one or more datasets as already registered in Biblio. <a href="https://onderzoektips.ugent.be/en/tips/00002061/" target="_blank">View documentation <i class="if if--small if-external-link
Same "as".

2024-08-06 13:49 UTC, verheyenkoen commented on views/record_timestamp.go
> +	s += "."
Not sure this is right but can't test as this requires a system update to the record. Looks like if there is no last edit (`lastUpdatedBy == nil`), there will be two dots at the end.

2024-08-14 11:53 UTC, nics approved these changes

2024-08-14 11:53 UTC, merged